logLevel: info
readTimeout: 10s
writeTimeout: 10s
writeQueueSize: 512
udpMaxPayloadSize: 1472

rtsp: yes
rtspAddress: :8554
rtmp: no
hls: yes
hlsAddress: :8888
hlsEncryption: no
hlsServerKey: server.key
hlsServerCert: server.crt
hlsAllowOrigins:
  - "*"
hlsTrustedProxies: []
hlsAlwaysRemux: yes
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsDirectory: ""
hlsMuxerCloseAfter: 60s
webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins:
  - "*"
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: ""
webrtcIPsFromInterfaces: no
webrtcIPsFromInterfacesList: []
webrtcAdditionalHosts:
  - 106.52.68.95
webrtcICEServers2: []
srt: no

paths:
  auction-live:
    source: publisher
    sourceOnDemand: no
